const ERROR_CODE_BAD_REQUEST = 400;
const ERROR_CODE_NOT_FOUND = 404;
const ERROR_CODE_INTERNAL_SERVER = 500;

module.exports = { ERROR_CODE_BAD_REQUEST, ERROR_CODE_INTERNAL_SERVER, ERROR_CODE_NOT_FOUND };
